version: '2'
services:
    app:
        build: ./php
        ports:
            - "9000:80"
        environment:
            dpPATH: ${PATH}:/usr/local/bin:/root/.composer/vendor/bin
        depends_on:
            - app-db
        env_file: .env
    app-db:
        build: ./mysql
        env_file: .env
        volumes:
            - app-db:/var/lib/mysql
        ports:
            - "13306:3306"
    mailcatcher:
        build: ./mailcatcher
        restart: always
        ports:
            - "1025:1025"
            - "1080:1080"
        environment:
            MAILCATCHER_PORT: 1025
        depends_on:
            - app
volumes:
    app-db:
        driver: local
